# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lyf/mirage01a_msm8939_64/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES +=     vendor/lyf/mirage01a_msm8939_64/proprietary/lib/libaudiso:obj/lib/libaudio.so     vendor/lyf/kmirage01a_msm8939_64/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so

PRODUCT_COPY_FILES += \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/ADSP:system/ADSP \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Audio:system/Audio \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Bluetooth:system/Bluetooth \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Camera:system/Camera \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/lyf/mirage01a_msm8939_64/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.msm8916.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Camera:system/Camera \
    vendor/lyf/mirage01a_msm8939_64/proprietary/firmware:system/firmware \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/DRM:system/DRM \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/GPS:system/GPS \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/lyf/mirage01a_msm8939_64/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/priv-app/com.qualcomm.location/com.qualcomm.location.apk:system/priv-app/com.qualcomm.location/com.qualcomm.location.apk \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/bin/slim_ap_daemon:system/vendor/bin/slim_ap_daemon \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Graphics:system/Graphics \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Graphics:system/Graphics \
    vendor/lyf/mirage01a_msm8939_64/proprietary/firmware:system/firmware \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Listen:system/Listen \
    vendor/lyf/mirage01a_msm8939_64/proprietary/service:system/service \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Media:system/Media \
    vendor/lyf/mirage01a_msm8939_64/proprietary/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Perf:system/Perf \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/perfd:system/bin/perfd \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Postprocessing:system/Postprocessing \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libmm-abl.so:system/vendor/lib64/libmm-abl.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Qualcomm:system/Qualcomm \
    vendor/lyf/mirage01a_msm8939_64/proprietary/framework:system/framework \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Radio:system/Radio \
    vendor/lyf/mirage01a_msm8939_64/proprietary/app/qcrilmsgtunnel/qcrilmsgtunnel.apk:system/app/qcrilmsgtunnel/qcrilmsgtunnel.apk \
    vendor/lyf/mirage01a_msm8939_64/proprietary/app/shutdownlistener/shutdownlistener.apk:system/app/shutdownlistener/shutdownlistener.apk \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/lyf/mirage01a_msm8939_64/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    vendor/lyf/mirage01a_msm8939_64/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Signed:system/Signed \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Venus:system/Venus \
    vendor/lyf/mirage01a_msm8939_64/proprietary/(media):system/(media) \
    vendor/lyf/mirage01a_msm8939_64/proprietary/firmware:system/firmware \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/lyf/mirage01a_msm8939_64/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Thermal:system/Thermal \
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/lyf/mirage01a_msm8939_64/proprietary/#:system/# \
    vendor/lyf/mirage01a_msm8939_64/proprietary/Time:system/Time \
    vendor/lyf/mirage01a_msm8939_64/proprietary/services:system/services \
    vendor/lyf/mirage01a_msm8939_64/proprietary/app/TimeService/TimeService.apk:system/app/TimeService/TimeService.apk
    vendor/lyf/mirage01a_msm8939_64/proprietary/bin/time_daemon:system/bin/time_daemon
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so
    vendor/lyf/mirage01a_msm8939_64/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so
